--- 
images: 
  - "gcr.io/$PROJECT_ID/[SERVICE-NAME]:$COMMIT_SHA"
steps: 
  - 
    args: 
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/[SERVICE-NAME]:$COMMIT_SHA"
      - "."
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - push
      - "gcr.io/$PROJECT_ID/[SERVICE-NAME]:$COMMIT_SHA"
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - run
      - deploy
      - "[SERVICE-NAME]"
      - "--image"
      - "gcr.io/$PROJECT_ID/[SERVICE-NAME]:$COMMIT_SHA"
      - "--region"
      - "[REGION]"
      - "--platform"
      - managed
    name: gcr.io/cloud-builders/gcloud
