steps:
- name: maven:3-jdk-8 
  entrypoint: mvn
  args: ['test']
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  timeout: '300s'