CREATE TABLE Catalog (
 ServiceID INT64 NOT NULL,
 ShopID INT64 NOT NULL,
 ServiceName STRING(MAX) NOT NULL,
 ServiceDescription STRING(MAX) NOT NULL,
 ImageURL STRING(MAX),
 FOREIGN KEY(ShopID) REFERENCES Shops(ShopID),
) PRIMARY KEY(ShopID, ServiceID),
 INTERLEAVE IN PARENT Shops ON DELETE CASCADE	
