CREATE TABLE Shops (
 ShopID INT64 NOT NULL,
 ShopName STRING(MAX) NOT NULL,
 Latitude FLOAT64 NOT NULL,
 Longitude FLOAT64 NOT NULL, 
 TypeOfService STRING(MAX) NOT NULL,
 AddressLine1 STRING(MAX) NOT NULL, 
) PRIMARY KEY(ShopID);
 
